#!/bin/bash
# NEXTFLOW TASK: reverse (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 2 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

function nxf_mktemp() {
    local base=${1:-/tmp}
    [[ $(uname) = Darwin ]] && mktemp -d $base/nxf.XXXXXXXXXX || mktemp -d -t nxf.XXXXXXXXXX -p $base
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /Users/bmpvieira/nextflow-playground/work/45/cfca282916a5acc752eb0cdd5bbfcb/.exitcode
  rm -f "$COUT" || true
  rm -f "$CERR" || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /Users/bmpvieira/nextflow-playground/work/45/cfca282916a5acc752eb0cdd5bbfcb/.command.begin
[ -f /Users/bmpvieira/nextflow-playground/work/45/cfca282916a5acc752eb0cdd5bbfcb/.command.env ] && source /Users/bmpvieira/nextflow-playground/work/45/cfca282916a5acc752eb0cdd5bbfcb/.command.env
rm -f seq_1
rm -f seq_2
rm -f seq_3
ln -s /Users/bmpvieira/nextflow-playground/work/67/062a5ecd074797ced562e4e9789d3d/seq_1 seq_1
ln -s /Users/bmpvieira/nextflow-playground/work/67/062a5ecd074797ced562e4e9789d3d/seq_2 seq_2
ln -s /Users/bmpvieira/nextflow-playground/work/67/062a5ecd074797ced562e4e9789d3d/seq_3 seq_3


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash -ue /Users/bmpvieira/nextflow-playground/work/45/cfca282916a5acc752eb0cdd5bbfcb/.command.sh
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
